name: Test

on: [ push, pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository 
      uses: actions/checkout@v2

    - name: Set up Go 1.20
      uses: actions/setup-go@v2
      with:
        go-version: "1.20"

    - name: Run tests
      run: find . -name go.mod -execdir go test -v ./... \;
